import type { AIInterviewReport } from '@devmeet/shared';
import { ArrowLeft, CheckCircle, Code, Clock, MessageSquare, Target } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

interface AIReportPanelProps {
  report: AIInterviewReport;
  onBack?: () => void;
}

export default function AIReportPanel({ report, onBack }: AIReportPanelProps) {
  const navigate = useNavigate();

  const handleBack = () => {
    if (onBack) onBack();
    else navigate('/dashboard');
  };

  const getScoreColor = (score: number) => {
    if (score >= 80) return '#10b981';
    if (score >= 60) return '#eab308';
    return '#ef4444';
  };

  const ScoreRing = ({ label, score, icon: Icon }: { label: string, score: number, icon: any }) => (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', background: '#18181b', padding: '20px', borderRadius: '12px', border: '1px solid var(--dm-border)' }}>
      <Icon size={24} style={{ color: '#a1a1aa', marginBottom: '10px' }} />
      <div style={{ fontSize: '32px', fontWeight: 800, color: getScoreColor(score) }}>
        {score}
      </div>
      <div style={{ fontSize: '13px', color: '#a1a1aa', marginTop: '5px' }}>{label}</div>
    </div>
  );

  return (
    <div style={{ height: '100vh', width: '100vw', background: 'var(--dm-bg)', overflowY: 'auto', padding: '40px' }}>
      <div style={{ maxWidth: '900px', margin: '0 auto' }}>
        <button onClick={handleBack} className="dm-btn-ghost" style={{ marginBottom: '20px' }}>
          <ArrowLeft size={16} style={{ marginRight: '8px' }} /> Back to Dashboard
        </button>

        <h1 style={{ color: 'white', fontSize: '32px', marginBottom: '10px' }}>Interview Report</h1>
        <p style={{ color: '#a1a1aa', marginBottom: '30px' }}>Generated by AI Interviewer</p>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', gap: '20px', marginBottom: '30px' }}>
          <ScoreRing label="Overall" score={report.overallScore} icon={Target} />
          <ScoreRing label="Correctness" score={report.correctnessScore} icon={CheckCircle} />
          <ScoreRing label="Approach" score={report.approachScore} icon={Target} />
          <ScoreRing label="Complexity" score={report.complexityScore} icon={Clock} />
          <ScoreRing label="Code Quality" score={report.codeQualityScore} icon={Code} />
          <ScoreRing label="Communication" score={report.communicationScore} icon={MessageSquare} />
        </div>

        <div style={{ background: '#18181b', padding: '24px', borderRadius: '12px', border: '1px solid var(--dm-border)', marginBottom: '30px' }}>
          <h2 style={{ color: 'white', fontSize: '18px', marginBottom: '15px' }}>AI Summary</h2>
          <p style={{ color: '#d4d4d8', lineHeight: '1.6' }}>{report.aiSummary}</p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '30px' }}>
          <div style={{ background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.2)', padding: '24px', borderRadius: '12px' }}>
            <h3 style={{ color: '#10b981', fontSize: '16px', marginBottom: '15px' }}>Strengths</h3>
            <ul style={{ color: '#d4d4d8', paddingLeft: '20px', margin: 0 }}>
              {report.strengths.map((s, i) => <li key={i} style={{ marginBottom: '8px' }}>{s}</li>)}
            </ul>
          </div>
          <div style={{ background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.2)', padding: '24px', borderRadius: '12px' }}>
            <h3 style={{ color: '#ef4444', fontSize: '16px', marginBottom: '15px' }}>Areas for Improvement</h3>
            <ul style={{ color: '#d4d4d8', paddingLeft: '20px', margin: 0 }}>
              {report.weaknesses.map((w, i) => <li key={i} style={{ marginBottom: '8px' }}>{w}</li>)}
            </ul>
          </div>
        </div>

        <div style={{ background: '#18181b', padding: '24px', borderRadius: '12px', border: '1px solid var(--dm-border)' }}>
          <h2 style={{ color: 'white', fontSize: '18px', marginBottom: '15px' }}>Suggestions</h2>
          <ul style={{ color: '#d4d4d8', paddingLeft: '20px', margin: 0 }}>
            {report.suggestions.map((s, i) => <li key={i} style={{ marginBottom: '8px' }}>{s}</li>)}
          </ul>
        </div>
      </div>
    </div>
  );
}
